services:
  api:
    build: .
    container_name: renfe-api
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./models:/app/models

  streamlit:
    image: python:3.11-slim
    container_name: renfe-streamlit
    working_dir: /app
    volumes:
      - ./streamlit_app:/app
    ports:
      - "8501:8501"
    command: bash -c "pip install streamlit requests && streamlit run app.py --server.address 0.0.0.0"
    environment:
      - API_URL=http://api:8000
    depends_on:
      - api

  mlflow:
    image: python:3.11-slim
    container_name: renfe-mlflow
    working_dir: /app
    volumes:
      - ./mlruns:/app/mlruns
    ports:
      - "5000:5000"
    command: bash -c "pip install mlflow && mlflow ui --host 0.0.0.0 --port 5000 --backend-store-uri ./mlruns"
